server:
  port: 8087

spring:
  application:
    name: risk-service

  datasource:
    url: jdbc:postgresql://localhost:5432/risk_db
    username: bank_user
    password: bank_pass

  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true

  kafka:
    bootstrap-server: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

resilience4j:

  circuitbreaker:

    instances:

      marketData:

        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      portfolio:

        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50

      account:

        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50

  retry:

    instances:

      marketData:

        maxAttempts: 3
        waitDuration: 2s

      portfolio:

        maxAttempts: 3
        waitDuration: 2s

      account:

        maxAttempts: 3
        waitDuration: 2s

risk:

  max-trade-amount: 1080000

  supported-symbols:

    - INS
    - FBC
    - DAX
    - FNB
    - GMARK

  blacklisted-symbols:

    - TEST
    - FAKE

  market:

    open: "11:50"
    close: "19:35"



  cloud:

    openfeign:

      client:

        config:

          default:

            connectTimeout: 3000

            readTimeout: 5000

            loggerLevel: basic

            compression:

              request:
                enabled: true

              response:
                enabled: true

