server:
  port: 8081


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: bank_user
    password: bank_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


  jwt:
    sercret: 6a8d7f2b1c4e9a5d6f8b3c7e1a9d4f6b8c2e5f7a1d3c9b6e8f4a2d7c1b5e9f3
    expiration: 86400000

