server:
  port: 8086

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgres://localhost:5432/notification_db
    username: bank_user
    password: bank_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: notification-service
#      auto-offset-reset: earliest
#
#
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#
#      properties:
#        spring.json.trusted.packages: org.bank.sharedevents.event



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

