package org.bank.riskservice.model;

public enum RiskRejectionReason {
    NONE,

    INSUFFICIENT_AVAILABLE_BALANCE,

    POSITION_LIMIT_EXCEEDED,

    DAILY_EXPOSURE_EXCEEDED,

    MAX_TRADE_AMOUNT_EXCEEDED,

    UNSUPPORTED_SYMBOL,

    BLACKLISTED_SYMBOL,

    MARKET_CLOSED,

    INVALID_QUANTITY,

    RISK_PROFILE_NOT_ALLOWED,

    SERVICE_UNAVAILABLE,
    HIGH_VOLATILITY
}
