server:
  port: 8083




spring:
  application:
    name: transfer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/transfer_db
    username: bank_user
    password: bank_pass

  spring:
    kafka:
      producer:
        properties:
          spring.json.add.type.headers: true


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  cloud:
    openfeign:
      client:
        config:
          account-service:
            connectTimeout: 3000
            readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



resilience4j:
  circuitbreaker:
    instances:
      account-service:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      accountService:
        maxAttempts: 3
        waitDuration: 1s


