server:
  port: 8087



spring:
  application:
    name: portfolio-service

  kafka:
    bootstrap-servers: 9092

    consumer:
      group-id: portfolio-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: org.bank.sharedevents.event.trade.TradeExecutedEvent

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: bank_user
    password: bank_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
